/*
 *
 * SettingsPage constants
 *
 */

export const DEFAULT_ACTION = 'app/SettingsPage/DEFAULT_ACTION';
export const SETTINGS_INIT = "GL/SETTINGS/INIT";
export const SETTINGS_FETCH = "GL/SETTINGS/FETCH";
export const SETTINGS_FETCH_OK = "GL/SETTINGS/FETCH/OK";
export const SETTINGS_FETCH_KO = "GL/SETTINGS/FETCH/KO";
export const SETTINGS_COY_SET = "GL/SETTINGS/COMPANY/SET";
export const SETTINGS_COY_ADD = "GL/SETTINGS/COMPANY/ADD";
export const SETTINGS_COY_DEL = "GL/SETTINGS/COMPANY/DEL";
export const SETTINGS_UIDATA_SET = "GL/SETTINGS/UIDATA/SET";

export const SETTINGS_SEG_SET = "GL/SETTINGS/SEGMENT/SET"
export const SETTINGS_SEG_ADD = "GL/SETTINGS/SEGMENT/ADD"
export const SETTINGS_SEG_DEL = "GL/SETTINGS/SEGMENT/DEL"

export const SETTINGS_CCY_SET = "GL/SETTINGS/CCY/SET"
export const SETTINGS_PRD_SET = "GL/SETTINGS/GLPERIOD/SET"

export const SETTINGS_SAVE_RQST = "GL/SETTINGS/SAVE/REQUEST"
export const SETTINGS_SAVE_OK = "GL/SETTINGS/SAVE/OK"
export const SETTINGS_SAVE_KO = "GL/SETTINGS/SAVE/KO"
export const SETTINGS_SAVE_CLEAR = "GL/SETTINGS/SAVE/KO"
export const SETTINGS_SAVE_OK_MSG = "Settings successfully saved."
export const SETTINGS_SAVE_RQST_MSG = "Saving settings, please wait..."

export const SETTINGS_MSG_SET = "GL/SETTINGS/MSG/SET"
export const SETTINGS_MSG_CLEAR = "GL/SETTINGS/MSG/CLEAR"

